services:
  nginx:
    image: nginx
    container_name: nginx-cache-demo
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/etc/nginx/html
    ports:
      - '8080:8080'
      - '8081:8081'
